name: Publish

on:
    release:
        types: [published]

permissions:
    contents: read
    id-token: write

jobs:
    publish:
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - uses: actions/checkout@v6

            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
                  registry-url: https://registry.npmjs.org

            - uses: actions/setup-node@v6
              with:
                  node-version: latest
                  registry-url: https://registry.npmjs.org

            - run: bun --bun install --ignore-scripts

            - run: bun --bun run test

            - run: bun --bun run build

            - run: npm publish --provenance --access=public
